from svmutil import *
print("this is c = 1 Model:")
trainy, trainx = svm_read_problem("train.txt")
testy, testx = svm_read_problem("test.txt")
model1 = svm_train(trainy, trainx, '-t 0 -c 1')
print("test :")
p_label1, p_acc1, p_val1 = svm_predict(testy, testx, model1)
print(p_label1)
print('#########################')
print("this is c = 100 Model:")
model2 = svm_train(trainy, trainx, '-t 0 -c 100')
print("test :")
p_label2, p_acc2, p_val2 = svm_predict(testy, testx, model2)
print(p_label2)
print('#########################')
print("this is c = 10000 Model:")
model3 = svm_train(trainy, trainx, '-t 0 -c 10000')
print("test :")
p_label3, p_acc3, p_val3 = svm_predict(testy, testx, model3)
print(p_label3)
print('#########################')
print("this is c = 1000000 Model:")
model4 = svm_train(trainy, trainx, '-t 0 -c 1000000')
print("test :")
p_label4, p_acc4, p_val4 = svm_predict(testy, testx, model4)
print(p_label4)
print('#########################')
print("this is c = 100000000 Model:")
model5 = svm_train(trainy, trainx, '-t 0 -c 100000000')
print("test :")
p_label5, p_acc5, p_val5 = svm_predict(testy, testx, model5)
print(p_label5)
print('#########################')